# Header
menu:
  Home: /
  About: /about
  Contact:

# Favicon
favicon_url: images/brainspill.svg

# Default Image for Posts
default_cover_image: images/default.jpg

# Google Analytics Tracking ID
google_analytics: UA-93892722-1


# Social Accounts
email_url: 
twitter_url: https://twitter.com/?lang=en
facebook_url: https://www.facebook.com/
instagram_url: https://www.instagram.com/
linkedin_url: https://www.linkedin.com/
dribbble_url:
github_url:
googleplus_url:
behance_url:
fivehundredpx_url:

# Disqus comments
disqus_shortname: blog-taylorjdawson-com
