# Header
menu:
  Home: /
  About: /about
  Contact:

# Favicon
favicon_url: images/brainspill.svg

# Default Image for Posts
default_cover_image: images/default.jpg

# Google Analytics Tracking ID
google_analytics: UA-93892722-1


# Social Accounts
email_url: 
twitter_url: https://twitter.com/TaylorJDawson_
facebook_url:
instagram_url: 
linkedin_url: 
dribbble_url:
github_url:
googleplus_url:
behance_url:
fivehundredpx_url:

# Disqus comments
disqus_shortname: blog-taylorjdawson-com
